---

version: "3.5"

services:
  chat_fastapi:
    image: hipposysai/airflow-mcp-fastapi:latest
    container_name: chat_fastapi
    env_file:
      - langchain-fastapi.env
    ports:
      - "8080:8080"
    networks:
      - data-lake-network 
  mcp_sse_server:
    image: hipposysai/airflow-mcp:latest
    container_name: mcp_sse_server
    env_file:
      - airflow-mcp.env
    ports:
      - "8081:8000"
    networks:
      - data-lake-network 

networks:
  prod-network:
    driver: bridge