---

version: "3.5"

services:
  chat_fastapi:
    image: hipposysai/airflow-mcp-fastapi:latest
    container_name: chat_fastapi
    env_file:
      - prod.env
    ports:
      - "8080:8080"
    networks:
      - prod-network
  chat_mcp:
    image: hipposysai/airflow-mcp:latest
    environment:
      TRANSPORT_TYPE: sse
      POST_MODE: 'false'
    container_name: chat_mcp
    env_file:
      - prod.env
    ports:
      - "8081:8000"
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge